### ISSUE TITLE
Test App\Tests\App\Storage\RrdCachedStorageTest::testUpdateWithNewDatasource fails randomly

### ISSUE THREAD

**Issue by jimmycleuren** [jimmycleuren/fireping#297]
1) App\Tests\App\Storage\RrdCachedStorageTest::testUpdateWithNewDatasource
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => 'median'
     1 => 'loss'
+    2 => 'new'
 )
/home/travis/build/jimmycleuren/fireping/tests/App/Storage/RrdCachedStorageTest.php:106

**Comment by kevinreniers** [comment]
Fixed in #300
