### ISSUE TITLE
Sonata vs. EasyAdmin

### ISSUE THREAD

**Issue by kevinreniers** [jimmycleuren/fireping#33]
EasyAdmin shows its limits when you cannot easily perform bulk actions. This makes management difficult in large fireping masters with lots of domains.

Considering we don't enforce unique names on domains, this makes it very easy for users to make an error and pollute the database. Cleaning up after this becomes very difficult.

Investigate whether Sonata is a viable alternative to this, because it includes a lot more options by default, such as bulk actions.

Reference: https://symfony.com/doc/master/bundles/SonataAdminBundle

**Comment by kevinreniers** [comment]
We decided to go 100% for EasyAdminBundle. :-)

**Comment by Mohammed-aziar** [comment]
Who is better and what are the differences between SonataAdmin and EysaAdmin ?
And explain why you decided to use EysaAdmin 100% ?
And thank you very much @kevinreniers .

**Comment by FractalizeR** [comment]
I'm also interested ;)
