### ISSUE TITLE
Slave logrotate

### ISSUE THREAD

**Issue by kevinreniers** [jimmycleuren/fireping#35]
Slaves currently do not do logrotating. We should include a template as well as an instruction in the INSTALL file.

**Comment by cgkkevinr** [comment]
```
/opt/fireping/var/logs/*.log {
    daily
    missingok
    rotate 7
    compress
    create 644 root root
}
```

Because the path `/opt/fireping/var/logs/` depends on where fireping is installed, the path can be different.

**Comment by cgkkevinr** [comment]
Need to update all slaves to include this now.
smoky01 has already been done.

**Comment by cgkkevinr** [comment]
Should also include logrotate in Docker: https://github.com/jimmycleuren/fireping/blob/master/Dockerfile

**Comment by kevinreniers** [comment]
Closing this because it's already mentioned in our install documentation.
