### ISSUE TITLE
Load distribution among different queues

### ISSUE THREAD

**Issue by cgkkevinr** [jimmycleuren/fireping#39]
When the amount of data that needs to be processed because too large we cannot complete it with one poster during one update window.

Because of the nature of the data that needs to be sent (time-sensitive) we need to guarantee that data is delivered in-order.

In order to handle the amount of data that gets sent, we need to distribute it among different queues, each with their own worker responsible for sending the data. We need to ensure that the same devices are always given to the same queues with the same poster, to avoid data from arriving out of order.

**Comment by jimmycleuren** [comment]
Fixed in #49
