### ISSUE TITLE
Duplicate ip with running slave

### ISSUE THREAD

**Issue by jimmycleuren** [jimmycleuren/fireping#41]
When a slave is running and it's config is updated with a duplicate ip, 1 of the 2 entries show up as unreachable

**Comment by jimmycleuren** [comment]
Restarting the slave seems to fix the issue

**Comment by kevinreniers** [comment]
Hey, I cannot reproduce this issue locally by adding or removing devices in-between configuration changes. Please reopen if this is still an issue and if you have a way to reproduce this.
