### ISSUE TITLE
Add capacity limit per slave

### ISSUE THREAD

**Issue by kevinreniers** [jimmycleuren/fireping#517]
Research if possible. This may be a manual task.

Prevent oversubscription of slaves by setting a maximum work capacity. This should come in the form of specifying which tasks a slave can do and how many it can do.

i.e.

Slave X -
 - ping: 10 000
 - traceroute: 2 000
 - http: 5 000

Adding more domains/devices or probes on either of these that would exceed this number will generate alerts and prevent the slave from receiving that many of them.

**Comment by jimmycleuren** [comment]
Is there even a way to predict or calculate this objectively ?
Not only the probe matters here, but also the number of samples for example. And even with that info, the load can vary a lot between identical slaves according to the config:
- The slave has a bad connection to the master and has to buffer a lot of results, it will use a lot more ram
- A traceroute with the same path every cycle is a lot more lightweigt than a different path every cycle
- ...

**Comment by kevinreniers** [comment]
You're right, this simply isn't practical and it should be left to the people who installing/maintaining a Fireping instance to keep track of this instead.

Won't fix.
