### ISSUE TITLE
Restrict changes to ProbeArchive

### ISSUE THREAD

**Issue by cgkkevinr** [jimmycleuren/fireping#55]
We should not allow changes to ProbeArchive. It will break RRDs.
Instead, we should insert the creation of a ProbeArchive into the creation of a Probe.

Then, we can make the overview of ProbeArchives read-only and prevent people from breaking them accidentally.

**Comment by jimmycleuren** [comment]
Added the app:rrd:validate command which will use rrdtune to adjust rrd files to the new archive settings.
